version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=tbriggs
    ports:
      - '5432:5432'

  app:
    build: common
    ports:
      - "5000:5000"

  web:
    container_name: web-dev
    image: app-dev
    build:
      context: frontend
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 3000:3000

  portainer_io:
    image: portainer/portainer-ce:2.11.1
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "9443:9443"
    command: --admin-password "$$2y$$05$$cPeAv0dpEhMWbrwaYaLPteJVnZjSvaa34CK.Zx8Ugwh/DhVtZvVDS"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock.ro
      - ./portainer-data:/data
    container_name: portainer